// =============================================================================
// 00_Config.js — Configurações centrais e cache em memória
// =============================================================================

const CFG = {
        SPREADSHEET_ID: "11L0-jgTgMA3JOyuUfowsOzZ0svnC3AegNgekTA62LmI",
        INPUT_SHEET_NAME: "Input",
        HIST_SHEET_NAME: "GE - Histórico",
        TIMEZONE: "America/Sao_Paulo",
        INPUT_SHEET: "Input",
        OUT_TOP: "Top 20 Termos",
        OUT_MACRO: "Macrotema",
        OUT_SUB: "Subtema",
        OUT_TIME: "Minuto a Minuto",
        OUT_HISTORICO: "Histórico",
        JA_AUTO_RUN_HOUR: 15,
        JA_AUTO_RUN_MINUTE: 0,
        JA_START_HOUR: 11,
        JA_START_MINUTE: 6,
        JA_END_HOUR: 12,
        JA_END_MINUTE: 59,
        JA_DIVISAO_REDE_MINUTE: 59,
        JA_CHANNEL_ID: "UCZaOZdn-Y-I5ikrofkWBLgQ",
        JA_UPLOADS_PLAYLIST_ID: "UUZaOZdn-Y-I5ikrofkWBLgQ",
        JA_TITLE_PATTERN: "[AO VIVO] JOGO ABERTO",
        GE_INPUT_SHEET: "Input",
        GE_OUT_TOP: "GE - Top 20 Termos",
        GE_OUT_MACRO: "GE - Macrotema",
        GE_OUT_SUB: "GE - Subtema",
        GE_OUT_TIME: "GE - Minuto a Minuto",
        GE_OUT_HISTORICO: "GE - Histórico",
        GE_OUT_MEDIA_TEMA: "GE - Média por Minuto TEMA",
        GE_AUTO_RUN_HOUR: 21,
        GE_AUTO_RUN_MINUTE: 0,
        IMPORT_TRIGGER_HOUR: 19,
        IMPORT_TRIGGER_MINUTE: 5,
        IMPORT_RETRY_TRIGGER_HOUR: 19,
        IMPORT_RETRY_TRIGGER_MINUTE: 10,
        GE_START_HOUR: 18,
        GE_START_MINUTE: 0,
        GE_END_HOUR: 18,
        GE_END_MINUTE: 59,
        GE_CHANNEL_ID: "UCcndglQZmXnYjgE_Grqt5yg",
        GE_UPLOADS_PLAYLIST_ID: "UUcndglQZmXnYjgE_Grqt5yg",
        GE_TITLE_PATTERN: "Gazeta Esportiva | AO VIVO",
        GE_APRESENTADORAS: ["MICHELLE", "MARINA"],
        EMAIL_DESTINO: "tssouza@tssouza.com",
        EMAIL_ENABLED: !0,
        TRANSCRIPTION_SERVER: "",
        SPEECH_SOURCE_MODE: "DRIVE",
        SPEECH_DRIVE_FOLDER_ID: "1yYZf8oyRcBfEwUy_9_vuZIJxExYwEpGz",
        SPEECH_WEBHOOK_ENABLED: !0,
        SPEECH_DRIVE_FILE_PREFIX: "transcricao",
        SPEECH_ALERT_ON_MISSING: !1,
        SPEECH_PROCESSED_PREFIX: "speech_processed_",
        AUTO_RUN_HOUR: 15,
        AUTO_RUN_MINUTE: 0,
        PROGRAM_START_HOUR: 11,
        PROGRAM_START_MINUTE: 6,
        PROGRAM_END_HOUR: 12,
        PROGRAM_END_MINUTE: 59,
        DIVISAO_REDE_MINUTE: 59,
        OPENAI_ENDPOINT: "https://api.openai.com/v1/chat/completions",
        OPENAI_MODEL: "gpt-4o",
        LLM_ENABLED: !0,
        LLM_BATCH_SIZE: 30,
        LLM_TEMPERATURE: 0,
        LLM_MAX_TOKENS: 4096,
        GEMINI_ENDPOINT: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent",
        GEMINI_MODEL: "gemini-2.0-flash-lite",
        API_FOOTBALL_ENDPOINT: "https://v3.football.api-sports.io",
        TEAM_IDS: {
            CORINTHIANS: 131,
            PALMEIRAS: 121,
            "SÃO PAULO": 126,
            SANTOS: 128,
            FLAMENGO: 127,
            FLUMINENSE: 124,
            VASCO: 133,
            BOTAFOGO: 120,
            INTERNACIONAL: 119,
            GRÊMIO: 130,
            "ATLÉTICO-MG": 1062,
            CRUZEIRO: 129,
            BAHIA: 118,
            FORTALEZA: 1193,
            "ATHLETICO-PR": 134,
            BRAGANTINO: 1154
        },
        TOP_TERMS_PER_MINUTE: 5,
        THEME_CARRY_MINUTES: 10,
        CARRY_MIN_CONFIDENCE: .55,
        MERCHAN_EXPLICIT_THRESHOLD: 8,
        MERCHAN_IMPLICIT_THRESHOLD: 12,
        MERCHAN_CARRY_MINUTES: 2,
        SMOOTH_WINDOW: 3,
        FIXED_THEMES: ["FLAMENGO", "PALMEIRAS", "CORINTHIANS", "SÃO PAULO", "SANTOS", "VASCO", "FLUMINENSE", "BOTAFOGO", "INTERNACIONAL", "GRÊMIO", "ATLÉTICO-MG", "CRUZEIRO", "BAHIA", "VITÓRIA", "FORTALEZA", "CEARÁ", "ATHLETICO-PR", "CORITIBA", "GOIÁS", "SPORT", "BRAGANTINO", "TORINO", "LIVERPOOL", "INTER DE MILÃO", "NFL", "NBA", "FUTSAL", "VÔLEI", "MMA", "OUTROS_ESPORTES", "MERCHAN", "GERAL"]
    },
    MEMORY_CACHE = {
        entityLexicon: null,
        stopwords: null
    };